---
- hosts: localhost
  gather_facts: true
  vars:
    JAVA_HOME: "/usr/lib/jvm/jre-1.8.0-openjdk.x86_64"
    app_name: simple-webapp.war
  roles:
    - jws
    - sabre1041.redhat-csp-download
  tasks:

    - name: "Check that required parameters are provided"
      ansible.builtin.assert:
        that:
          - app_url is defined
          - app_url != ""
        quiet: true

    - name: Check is port 8080 is open
      ansible.builtin.wait_for:
        host: localhost
        port: 8080
        state: started
        delay: 0
        timeout: 3

    - name: Deploy the demo app
      ansible.builtin.get_url:
        url: "{{ app_url }}"
        dest: "{{ jws.catalina.home }}/{{ app_name }}"
        force: yes
      notify: restart tomcat service

    - name: Check is port 8080 is open after restart
      ansible.builtin.wait_for:
        host: localhost
        port: 8080
        state: started
        delay: 0
        timeout: 3

  handlers:
    - name: restart tomcat service
      ansible.builtin.service:
        name: jws5-tomcat.service
        state: restarted
