---
- name: "Check that required parameters are provided"
  ansible.builtin.assert:
    that:
      - app_url is defined
      - app_url != ""
      - jws_home is defined
      - jws_home != ""
    quiet: true

- ansible.builtin.stat:
    path: "{{ jws_home }}"
  register: tc_home

- ansible.builtin.debug:
    msg: "{{ tc_home }}"

- ansible.builtin.assert:
    that:
      - tc_home is defined
      - tc_home.stat is defined
    quiet: true

- name: Start Tomcat service
  ansible.builtin.systemd_service:
    name: tomcat
    state: started

- name: Deploy the demo app
  ansible.builtin.get_url:
    url: "{{ app_url }}"
    dest: "{{ jws_home }}/webapps/{{ app_name }}"
    force: yes
  notify: Restart Tomcat service
