---
- name: "Check that required parameters are provided"
  ansible.builtin.assert:
    that:
      - app_url is defined
      - app_url != ""
      - tomcat_home is defined
      - tomcat_home != ""
    quiet: true

- ansible.builtin.stat:
    path: "{{ tomcat_home }}"
  register: tc_home

- ansible.builtin.debug:
    msg: "{{ tc_home }}"

- ansible.builtin.assert:
    that:
      - tc_home is defined
      - tc_home.stat is defined
      - tc_home.stat.exists
      - tc_home.stat.isdir 
    quiet: true

- name: Deploy the demo app
  ansible.builtin.get_url:
    url: "{{ app_url }}"
    dest: "{{ tomcat_home }}/webapps/{{ app_name }}"
    force: yes
  notify: Restart Tomcat service
