---

- name: "Install JWS with package {{ jws.package }}"
  ansible.builtin.command: "yum group -y install {{ jws.package }}"
  when:
    - jws.package is defined

- name: Enable tomcat service
  ansible.builtin.service:
    name: jws5-tomcat.service
    enabled: yes

- name: start tomcat service
  ansible.builtin.service:
    name: jws5-tomcat.service
    state: started
