---
- stat:
    path: "{{ jws.catalina.home }}"
  register: jws_install_dir

- name: "Install JWS with package {{ jws.package }}"
  ansible.builtin.command: "yum group -y install {{ jws.package }}"
  when:
    - jws.package is defined
    - jws_install_dir.stat is defined
    - not jws_install_dir.stat.exists

- name: "Install JWS with zipfile from RHN: {{ jws.rhn_url }}"
  redhat_csp_download:
    url: "{{ jws.rhn_url }}"
    dest: "{{  jws.catalina.home }}"
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
  register: csp_jboss_eap_download
  when:
    - jws.rhn_url is defined
    - jws_install_dir.stat is defined
    - not jws_install_dir.stat.exists

- name: Enable tomcat service
  ansible.builtin.service:
    name: jws5-tomcat.service
    enabled: yes

- name: start tomcat service
  ansible.builtin.service:
    name: jws5-tomcat.service
    state: started
