---
- stat:
    path: /usr/bin/katello-rhsm-consumer
  register: is_katello_installed

- block:
  - get_url:
      url: "{{ jws.katello.rpm.url }}"
      dest: "{{ jws.katello.rpm.dest }}"
      validate_certs: no

  - name: Install the katello rpm
    shell: rpm -Uvh "{{ jws.katello.rpm.dest }}" --force
    ignore_errors: yes
  when:
    - is_katello_installed is defined
    - is_katello_installed.stat is defined
    - not is_katello_installed.stat.exists

- name: Register the node to the Satellite 6 server
  command: subscription-manager register --org="JBoss_Toronto" --activationkey="ansible-middleware" --force

- name: Subscribe to JBoss Web Server CDN repositories
  shell: subscription-manager repos --enable="{{ item }}"
  loop:
    - jws-5-for-rhel-8-x86_64-rpms

- name: Install JBoss Web Server
  yum:
    name: "@jws5"
    state: latest

- name: Enable tomcat service
  ansible.builtin.service:
    name: jws5-tomcat.service
    enabled: yes

- name: start tomcat service
  ansible.builtin.service:
    name: jws5-tomcat.service
    state: started
